version: '3.6'

services:
  peatio:
    build:
      context: ../app/peatio
    depends_on:
      - proxy
      - db
      - redis
      - rabbitmq
      - barong
      - ranger
      - geth
      - coinhub
    env_file:
      - ../config/peatio.env
    expose:
      - "8000"
    volumes:
      - peatio-assets:/home/app/public
      - ../config/peatio:/opt/peatio/config:ro
      - ../app/peatio/app:/home/app/app
      - ../app/peatio/lib:/home/app/lib
    command: bash -c "bin/link_config && bundle exec puma --config config/puma.rb"

  rangda:
    build:
      dockerfile: Dockerfile.dev
      context: ../app/rangda
    ports:
      - 8010:8080

  barong:
    build:
      context: ../app/barong
    depends_on:
      - proxy
      - db
      - vault
      - mailcatcher
    env_file:
      - ../config/barong.env
    volumes:
      - barong-assets:/home/app/public
      - ../config/barong:/opt/barong/config:ro
      - ../app/barong/app:/home/app/app
      - ../app/barong/lib:/home/app/lib
    expose:
      - "8001"

  assets:
    image: nginx
    depends_on:
      - peatio
      - barong
      - proxy
    volumes:
     - peatio-assets:/usr/share/nginx/html/assets/peatio:ro
     - barong-assets:/usr/share/nginx/html/assets/barong:ro
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: www.wb.local; PathPrefix: /assets'
      traefik.port: 80

volumes:
  peatio-assets:
  barong-assets:
