version: '3'

services:
  peatio:
    build:
      context: ../app/peatio
    depends_on:
      - db
      - redis
      - rabbitmq
      - smtp_relay
      - peatio_daemons
      - barong
    ports:
      - 8000
    env_file:
      - ../config/peatio.env
    volumes:
      - ../config/peatio:/opt/peatio/config:ro

  peatio_daemons:
    build:
      context: ../app/peatio
    depends_on:
      - db
      - redis
      - rabbitmq
      - coinhub
    ports:
      - 8080
    env_file:
      - ../config/peatio.env
    volumes:
      - ../config/peatio:/opt/peatio/config:ro
    command: god -c lib/daemons/daemons.god -D start

  peatio-trading-ui:
    build:
      context: ../app/peatio-trading-ui
    depends_on:
      - peatio
    ports:
      - 3000
    env_file:
      - ../config/peatio-trading-ui.env

  barong:
    build:
      context: ../app/barong
    depends_on:
      - db
      - vault
    ports:
      - 8001
    env_file:
      - ../config/barong.env
    volumes:
      - ../config/barong:/opt/barong/config:ro
