version: '3'

services:

  coinhub:
    image: rubykube/coinhub

  smtp_relay:
    image: kaigara/postfix:latest
    volumes:
      - ../config/smtp-relay.yaml:/etc/kaigara/metadata/relay.yml

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: changeme

  redis:
    image: redis:4.0.10
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.7.6-management
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "15672:15672"

  vault:
    image: vault:0.10.2
    environment:
      SKIP_SETCAP: 1
      VAULT_TOKEN: changeme
      VAULT_DEV_ROOT_TOKEN_ID: changeme
      VAULT_ADDR: http://vault:8200

  slanger:
    image: rubykube/slanger:0.2.3
    depends_on:
      - redis
    environment:
      REDIS_URL: redis://redis:6379
      APP_KEY: f9jxQLQ631LehgeAjjJZpg2iMiCeHAMW
      APP_SECRET: bMoWeyjId0iSabGF6EY3coVhTpjW3Hpt
    labels:
      traefik.enable: true
      traefik.ws.frontend.rule: 'Host: ws.slanger.wb.local'
      traefik.ws.port: 8080
      traefik.api.frontend.rule: 'Host: api.slanger.wb.local'
      traefik.api.port: 4567

volumes:
  db_data:
  rabbitmq_data:
  redis_data:
