version: '3.6'

services:
  geth:
    image: ethereum/client-go:stable
    restart: always
    command: |
      --syncmode=full
      --rinkeby
      --rpc
      --rpcaddr=0.0.0.0
      --rpcport=8545
      --port=30303
      --rpcapi="db,personal,eth,net,web3"
      --rpccorsdomain="*"
      --rpcvhosts="*"
    volumes:
      - eth-data:/root/.ethereum/
      - ../config/.eth-deposit-wallet.json:/root/.ethereum/rinkeby/keystore/UTC--2018-07-12T12-02-11.908581195Z--4b6a630ff1f66604d31952bdce2e4950efc99821
      - ../config/.eth-hot-wallet.json:/root/.ethereum/rinkeby/keystore/UTC--2018-07-12T11-58-12.739560580Z--45a31b15a2ab8a8477375b36b6f5a0c63733dce8
    expose:
      - "8545"
      - "30303"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: eth.wb.local'
      traefik.port: 8545

  bitcoind:
    image: kylemanna/bitcoind
    restart: always
    volumes:
      - ../config/bitcoin.conf:/bitcoin/.bitcoin/bitcoin.conf
      - btc-data:/bitcoin
    expose:
      - "18332"
      - "18333"
    labels:
      traefik.enable: true
      traefik.frontend.rule: 'Host: btc.wb.local'
      traefik.port: 18332

volumes:
  eth-data:
  btc-data:
